// Review/color-game/svelte/src/components/NavBar.svelte
<script>
import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();

  export let newGame;
  export let result;
  
  function restartGame(){
    dispatch('restartGame', {
      restartGame: true
    });
  }

</script>

<div class="nav">
  <button on:click={ restartGame }>
    { newGame }
  </button>
  <span>{ result }</span>
</div>

// Review/color-game/vue/src/components/NavBar.vue
<template>
  <div class="nav">
    <button @click="restartGame">{{ newGame }}</button>
    <span>{{ result }}</span>
  </div>
</template>
<script>
export default {
  props: {
    result: {
      type: String
    },
    newGame: {
      type: String
    }
  },
  methods: {
    restartGame() {
      this.$emit("restartGame", true);
    }
  }
};
</script>
