// Review/color-game/vue/src/components/ColorSquare.vue
<template>
  <div
    class="colorSquare"
    :style="`background-color:${color}`"
    @click="clickedColor"
  />
</template>

<script>
export default {
  props: {
    color: {
      type: String,
      required: true
    }
  },
  methods: {
    clickedColor(event) {
      this.$emit("clickedColor", event.srcElement.style.backgroundColor);
    }
  }
};
</script>

// Review/color-game/svelte/src/components/ColorSquare.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();

  export let color;
  
  function clickedColor(event){
    dispatch('clickedColor', {
      clickedColor: event.srcElement.style.backgroundColor
    });
  }

</script>

<div
  class="colorSquare"
  style="background-color:{color}"
  on:click={clickedColor}>
</div>
