// Review/color-game/vue/src/App.vue
<template>
  <div id="app">
    <Title :rgb="rgb" />
    <NavBar
      :result="result"
      :newGame="newGame"
      @restartGame="handleRestartGame"
    />
    <ColorContainer v-for="(color, i) in colors" :key="i">
      <ColorSquare :color="color" @clickedColor="handleClickedColor" />
    </ColorContainer>
  </div>
</template>

<script>
import "@/styles/index.css";

import ColorContainer from "@/components/ColorContainer";
import ColorSquare from "@/components/ColorSquare";
import NavBar from "@/components/NavBar";
import Title from "@/components/Title";

export default {
  name: "app",
  data: () => ({
    retrievedColor: null,
    result: null,
    rgb: null,
    newGame: null,
    colors: [],
    SQUARES_QUANTITY: 6
  }),
  components: {
    ColorContainer,
    ColorSquare,
    NavBar,
    Title
  },
  mounted() {
    this.initGame();
  },
  methods: {
    handleRestartGame(restart) {
      if (restart) {
        this.initGame();
        this.result = "";
        this.newGame = "";
      }
    },
    handleClickedColor(clickedColor) {
      if (clickedColor === this.retrievedColor) {
        this.result = "Correct 🎉🎊";
        this.newGame = "Play Again? 😊";
        this.changeColors(clickedColor);
        this.h1BgColor = clickedColor;
      } else {
        this.result = "Try Again 😞";
        setTimeout(() => {
          this.result = "";
        }, 800);
      }
    },
    initGame() {
      this.colors = this.createRandomColors(this.SQUARES_QUANTITY);
      this.retrievedColor = this.getColor(this.colors);
      this.rgb = this.retrievedColor;
    },
    getColor(colorsArray) {
      return colorsArray[this.mathRandom(colorsArray.length)];
    },
    changeColors(color) {
      this.colors = new Array(this.SQUARES_QUANTITY).fill(color);
    },
    createRandomColors(quantity) {
      let colorsArray = [];
      for (let i = 0; i < quantity; i++) {
        colorsArray.push(this.randomizeColor());
      }
      return colorsArray;
    },
    randomizeColor() {
      let r = this.mathRandom();
      let g = this.mathRandom();
      let b = this.mathRandom();
      return `rgb(${r}, ${g}, ${b})`;
    },
    mathRandom(multiplier = 256) {
      return Math.floor(Math.random() * multiplier);
    }
  }
};
</script>

// Review/color-game/svelte/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import ColorContainer from "./components/ColorContainer.svelte";
  import ColorSquare from "./components/ColorSquare.svelte";
  import NavBar from "./components/NavBar.svelte";
  import Title from "./components/Title.svelte";

  $: retrievedColor = null;
  $: result = null;
  $: rgb = null;
  $: newGame = null;
  let colors = [];
  const SQUARES_QUANTITY = 6;
  
  onMount(() => {
    initGame();
  })
  function handleRestartGame(event) {
    if (event.detail.restartGame) {
      initGame();
      result = "";
      newGame = "";
    }
  }

  function handleClickedColor(event) {
    let clickedColor = event.detail.clickedColor;

    if (clickedColor === retrievedColor) {
      result = "Correct 🎉🎊";
      newGame = "Play Again? 😊";
      changeColors(clickedColor);
      h1BgColor = clickedColor;
    } else {
      result = "Try Again 😞";
      setTimeout(() => {
        result = "";
      }, 800);
    }
  }

  function initGame() {
    colors = createRandomColors(SQUARES_QUANTITY);
    retrievedColor = getColor(colors);
    rgb = retrievedColor;
  }

  function getColor(colorsArray) {
    return colorsArray[mathRandom(colorsArray.length)];
  }

  function changeColors(color) {
    colors = new Array(SQUARES_QUANTITY).fill(color);
  }

  function createRandomColors(quantity) {
    let colorsArray = [];
    for (let i = 0; i < quantity; i++) {
      colorsArray.push(randomizeColor());
    }
    return colorsArray;
  }

  function randomizeColor() {
    let r = mathRandom();
    let g = mathRandom();
    let b = mathRandom();
    return `rgb(${r}, ${g}, ${b})`;
  }

  function mathRandom(multiplier = 256) {
    return Math.floor(Math.random() * multiplier);
  }
</script>

<div id="app">
  <Title rgb={rgb} />
  <NavBar
    result={result}
    newGame={newGame}
    on:restartGame={handleRestartGame}
  />
  <ColorContainer>
    {#each colors as color}
      <ColorSquare color={color} on:clickedColor={handleClickedColor} />
    {/each}
  </ColorContainer>
</div>
